## Global site settings.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, you should restart the server
# process. If you find yourself editing this file very often, consider using
# Jekyll's data files feature instead.
#
# These variables can be accessed by templates, e.g. ``{{ site.myvariable }}``.

## General metadata
title: Chris & Sarah
email: cbarrick1@example.com
tagline: Official website for the wedding of Chris Barrick and Sarah Colquhoun
description: >-
  Official website for the wedding of Chris Barrick and Sarah Colquhoun
timezone: America/New_York
lang: en-US
encoding: utf-8
permalink: /:title
license:
  spdx: CC-BY-SA-4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/

## Canonical URL
url: "https://wedding.cbarrick.dev"
baseurl: ""

## Build settings
markdown: kramdown
kramdown:
  input: Kramdown
sass:
  style: compressed

## Plugins
plugins:
  - jekyll-default-layout
